#!/bin/sh

# Set these paths appropriately

BIN=/home/meryll/git/ProjetExtractionConnaissance/Classification/bin
CMD=/home/meryll/git/ProjetExtractionConnaissance/Classification/cmd
LIB=/home/meryll/git/ProjetExtractionConnaissance/Classification/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
