#!/bin/sh

# Set these paths appropriately

BIN=/home/meryll/git/ProjetExtractionConnaissance/Classification/bin
CMD=/home/meryll/git/ProjetExtractionConnaissance/Classification/cmd
LIB=/home/meryll/git/ProjetExtractionConnaissance/Classification/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
